site_name: NightShift
site_url: https://rmic.github.io/nightshift/
theme:
  name: material
  language: fr
  palette: 

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
        
  features:
    - header.autohide
    - search.highlight
    - search.suggest
    - search.share
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.tabs
    - navigation.path
    - search.suggest
    - search.highlight
    - header.autohide
    - content.tooltips

nav:
  - "Introduction":
      - "Le métier d'ambulancier": introduction/introduction.md
      - "ATNUP - Transport Non Urgent": introduction/atnup.md
      - "AMU - Aide Médicale Urgente": introduction/amu.md
  
  - "Premiers secours":
      - "Règles essentielles d'intervention": 
          - "Sécurité": premiers_secours/rei/securite.md
          - "Bilan": premiers_secours/rei/bilan.md
          - "Appel": premiers_secours/rei/appel.md
          - "Soins": premiers_secours/rei/soins.md
      - "Malaises":
          - "Hypertension": premiers_secours/malaises/hypertension.md
          - "Hypothermie": premiers_secours/malaises/hypothermie.md
          - "AVC": premiers_secours/malaises/avc.md
          - "Épilepsie": premiers_secours/malaises/epilepsie.md
          - "Douleur thoracique": premiers_secours/malaises/douleur_thoracique.md
          - "Hyperthermie": premiers_secours/malaises/hyperthermie.md
          - "Hypotension": premiers_secours/malaises/hypotension.md
          - "Hyperglycémie": premiers_secours/malaises/hyperglycemie.md
          - "Hypoglycémie": premiers_secours/malaises/hypoglycemie.md
      - "Lésions de l'appareil locomoteur": premiers_secours/lesions_locomoteur.md
      - "Gestion des hémorragies": premiers_secours/hemorragies.md

  - "Ressources supplémentaires": ressources.md

plugins:
  - with-pdf:
      author: Raphael Michel
  - search

markdown_extensions:
  - admonition
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true




  